name: Feature CI

on:
  pull_request:
    branches: [ master ]


jobs:
  build:
    strategy:
      matrix:
        include:
        - name: Windows
          os: windows-latest
          mill: 'mill --no-server'
        - name: Linux
          os: ubuntu-latest
          mill: 'mill'

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Mill
      uses: yilinwei/setup-mill@master
      with:
        mill-version: 0.8.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Check formatting
      run: mill mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll __.sources
    - name: Setup up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Compile
      run: |
        ${{ matrix.mill }} server.compile
        ${{ matrix.mill }} client.fastOpt
        ${{ matrix.mill }} web.vendor
        ${{ matrix.mill }} web.sass
    - name: Run unit tests
      run: ${{ matrix.mill }} server.test
